In [64]:
from gym import envs
import numpy as np 


env = gym.make('Taxi-v2')
env._max_episode_steps = 40000
env.reset()

def policy_evaluation(policy, env, discount_factor, theta):
    
    V = np.zeros(env.nS)
    counter = 0
    while True: 
        counter += 1 
        delta = 0
        for s in range(env.nS): 
            vNew = 0
            for a in range(env.nA): 
                for prob, nextState, reward, done in env.P[s][a]:
                    vNew += policy[s][a] * prob * (reward + discount_factor * V[nextState])
                
            delta = max( delta, np.abs(V[s] - vNew))
            V[s] = vNew
        if delta < theta:
            break
                    

    return np.array(V)

def policy_iteration(env, discount_factor): 
    
    
    policy = np.ones([env.nS, env.nA]) / env.nA
    numItr = 0
    while True:
        numItr += 1 
        V = policy_evaluation(policy, env, discount_factor, 0.00001)
        policyStable = True 

        for s in range(env.nS):
            oldAction = np.argmax(policy[s])
           
            qValues = np.zeros( env.nA)
            for a in range(env.nA):
                for prob, nextState, reward, done in env.P[s][a]:
                    qValues[a] += prob * (reward + discount_factor * V[nextState])

            newAction = np.argmax(qValues)


            if oldAction != newAction:
                policyStable = False 
            policy[s] = np.zeros([env.nA])
            policy[s][newAction] = 1

        if policyStable:
            print(numItr)
            return policy, V
    return policy, np.zeros(env.env.S)

env.reset()
policyPI, valuePI = policy_iteration(env, 0.95)

print(policyPI)

print(valuePI)

11
[[0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1. 0.]
 ...
 [0. 1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]]
[184.61532028 130.41103094 146.66043063 122.8904623   90.56592283
 130.41103094  79.78572443  96.38515752 115.74596237  90.56590818
 146.66043063  96.38515752  79.78573908  90.56590818  79.78572443
 122.8904623  195.38455426 138.3274091  155.43204035 130.41102241
 174.38455426 122.89047939 138.3274091  115.74593919  96.38518853
 138.3274091   85.03761277 102.51070158 108.95866425  85.03761277
 138.3274091   90.56589965  85.03762669  96.38517461  85.03761277
 130.41102241 184.61532655 146.66043833 146.66043833 138.32740099
 146.66045155 102.51071782 115.74595542  96.3851665  115.74596865
 164.66531333 102.51071782 122.89047129 102.51073104  79.78573213
 130.41103864  85.03760466  90.5659291  102.51071782  90.56591588
 138.32740099 155.43206022 174.38454766 138.32741641 146.66043063
 138.32742897  96.38518193 108.95865765  90.56590818 122.89049927
 174.38